"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    ('resources', ['resources/icon.png'])
]
OPTIONS = {
    'argv_emulation': True,
    'packages': [],
    'iconfile': 'resources/icon.png',
    'plist': {
        'CFBundleName': 'Gigabyte M27Q Settings Controller',
        'CFBundleShortVersionString': '1.1.0',
        'CFBundleVersion': '1.1.0',
        'CFBundleIdentifier': 'com.mithwick93.gigabyte.m27q.settings.controller',
        'CFBundleIconFile': 'resources/icon',
        'LSUIElement': '1',
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
